version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Dashboard
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directories:
      - /tofu
      - /tofu/module
    schedule:
      interval: daily
