name: Build

on:
  push:
    branches:
      - main
    paths:
      - src/**/*.cs
      - src/**/*.csproj
      - src/**/package.nix
      - default.nix
      - lon.nix
      - lon.lock
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: drakon64
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: cachix watch-exec drakon64 -- nix-build -A server.docker

      - name: Create Cachix pins
        run: |
          cachix pin drakon64 anamnesis-server "$(nix eval --file ./default.nix server --raw --impure)" --keep-revisions 1
          cachix pin drakon64 anamnesis-server-docker "$(nix eval --expr '(import ./. {}).server.docker {}' --raw --impure)" --keep-revisions 1

      - run: docker load < result

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Server to GitHub Packages
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/drakon64/anamnesis-server:latest
        env:
          SOURCE_DATE_EPOCH: 0
