name: Build

on:
  push:
    branches:
      - main
    paths:
      - src/**/**.cs
      - src/**/*.csproj
      - src/**/package.nix
      - src/**/deps.json
      - src/**/Dockerfile
      - src/Dashboard/Pages/*.cshtml
      - default.nix
      - lon.nix
      - lon.lock
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: drakon64
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build
        run: cachix watch-exec drakon64 -- nix-build -A repository.docker -A dashboard.docker

      - name: Create Cachix pins
        run: |
          cachix pin drakon64 anamnesis "$(nix eval --expr '(import ./. {}).repository' --raw --impure)" --keep-revisions 1
          cachix pin drakon64 anamnesis-docker "$(nix eval --expr '(import ./. {}).repository.docker' --raw --impure)" --keep-revisions 1
          cachix pin drakon64 anamnesis-dashboard "$(nix eval --expr '(import ./. {}).dashboard' --raw --impure)" --keep-revisions 1
          cachix pin drakon64 anamnesis-dashboard-docker "$(nix eval --expr '(import ./. {}).dashboard.docker' --raw --impure)" --keep-revisions 1
        continue-on-error: true

      - run: |
          docker load < result
          docker load < result-2

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Repository to GitHub Packages
        uses: docker/build-push-action@v6
        with:
          context: src/Repository
          push: true
          tags: ghcr.io/drakon64/anamnesis:latest
        env:
          SOURCE_DATE_EPOCH: 0

      - name: Upload Dashboard to GitHub Packages
        uses: docker/build-push-action@v6
        with:
          context: src/Dashboard
          push: true
          tags: ghcr.io/drakon64/anamnesis-dashboard:latest
        env:
          SOURCE_DATE_EPOCH: 0

  Deploy:
    needs:
      - Build

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - name: Install Cachix
        uses: cachix/cachix-action@v16
        with:
          name: drakon64
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Nix shell
        run: nix-shell -A opentofu --run "exit"

      - uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy to Cloud Run
        run: |
          echo "$TERRAFORM_TFVARS" | base64 -d > terraform.tfvars
          nix-shell -A opentofu ../shell.nix --run "tofu init"
          nix-shell -A opentofu ../shell.nix --run "tofu apply -auto-approve -target module.anamnesis.google_cloud_run_v2_service.repository -target module.anamnesis.google_cloud_run_v2_service.dashboard"
        working-directory: tofu
        env:
          TERRAFORM_TFVARS: ${{ secrets.TERRAFORM_TFVARS }}
